# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiGateway2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e80764a122e14ccf8d87cc61cab5ed33 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0462b66b64d648b3a54839f649987749 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e80764a122e14ccf8d87cc61cab5ed33 }}/api-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiGateway2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b4bea1f2770e4d40a1b8014f1a9b017f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e80764a122e14ccf8d87cc61cab5ed33 }}/api-gateway:${{ github.sha }}'