# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiGateway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2d68c87649694d8ba0528e5469b0c3ad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ea109285b6d74392a3937b69bce51422 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2d68c87649694d8ba0528e5469b0c3ad }}/sof44/api_gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiGateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0dd5df3a83bd44d6af33a237da06100c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2d68c87649694d8ba0528e5469b0c3ad }}/sof44/api_gateway:${{ github.sha }}'